.TH "EarnShardsForCards.Test.Models.CardTest< T >" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Test.Models.CardTest< T > \- Tests the implementations of the Card class  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Tests the implementations of the Card class 


.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fICard\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
