.TH "EarnShardsForCards.Server.Areas.Identity.Pages.Account.LoginWith2faModel" 3 "Sat Apr 23 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Areas.Identity.Pages.Account.LoginWith2faModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputModel\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginWith2faModel\fP (SignInManager< \fBApplicationUser\fP > signInManager, UserManager< \fBApplicationUser\fP > userManager, ILogger< \fBLoginWith2faModel\fP > logger)"
.br
.ti -1c
.RI "async Task< IActionResult > \fBOnGetAsync\fP (bool rememberMe, string returnUrl=null)"
.br
.ti -1c
.RI "async Task< IActionResult > \fBOnPostAsync\fP (bool rememberMe, string returnUrl=null)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBInputModel\fP \fBInput\fP\fC [get, set]\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "bool \fBRememberMe\fP\fC [get, set]\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "string \fBReturnUrl\fP\fC [get, set]\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
