.TH "EarnShardsForCards.Shared.Data.GenericGameObjects.DiscardPile< T >" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Shared.Data.GenericGameObjects.DiscardPile< T > \- A \fBDiscardPile\fP represents the real-world pile of cards that grows throughout the play of the game\&. It is accessible from the top and is able to be cleared out\&. It can be used as a source of cards for various games\&. It may be at points empty and at other points full of cards\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiscardPile\fP ()"
.br
.RI "Create a discard pile with no cards "
.ti -1c
.RI "void \fBAdd\fP (T card, bool insertFaceUp=true)"
.br
.RI "Add a card to the top of this pile\&. "
.ti -1c
.RI "T \fBDraw\fP ()"
.br
.RI "Remove a card from the top and return it "
.ti -1c
.RI "string \fBGetImageFilePath\fP ()"
.br
.RI "Returns the current image representation for this pile\&. "
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Empties the discard pile of all of its cards but does not return them\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IList< \fBCard\fP > \fBCards\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "static string \fBEmptyImageRepresentation\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBDiscardPile\fP represents the real-world pile of cards that grows throughout the play of the game\&. It is accessible from the top and is able to be cleared out\&. It can be used as a source of cards for various games\&. It may be at points empty and at other points full of cards\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of card that this discard pile contains
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBCard\fP\fP
.SH "Member Function Documentation"
.PP 
.SS "void \fBEarnShardsForCards\&.Shared\&.Data\&.GenericGameObjects\&.DiscardPile\fP< T >\&.Add (T card, bool insertFaceUp = \fCtrue\fP)"

.PP
Add a card to the top of this pile\&. 
.PP
\fBParameters\fP
.RS 4
\fIcard\fP The card to be added
.br
\fIinsertFaceUp\fP Whether the card should be face up (true by default)
.RE
.PP

.SS "T \fBEarnShardsForCards\&.Shared\&.Data\&.GenericGameObjects\&.DiscardPile\fP< T >\&.Draw ()"

.PP
Remove a card from the top and return it 
.PP
\fBReturns\fP
.RS 4
The card removed and returned from the top of the pile
.RE
.PP

.SS "string \fBEarnShardsForCards\&.Shared\&.Data\&.GenericGameObjects\&.DiscardPile\fP< T >\&.GetImageFilePath ()"

.PP
Returns the current image representation for this pile\&. 
.PP
\fBReturns\fP
.RS 4
The image representation of this discard pile
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
