.TH "EarnShardsForCards.Shared.Data.Interfaces" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Shared.Data.Interfaces
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeck\fP"
.br
.RI "Interface for a game deck that identifies the common functions of each type of deck\&. "
.ti -1c
.RI "interface \fBIGinRummyController\fP"
.br
.RI "Represents the open functionality that can be taken a GinRummyController class by other classes\&. The main purpose of this interface is to allow a mock controller to be used for testing purposes\&. "
.ti -1c
.RI "interface \fBIMeld\fP"
.br
.RI "This \fBIMeld\fP represents melds (sets/runs) from the game, Gin Rummy\&. It provides the common functionality for the melds and allows them to be stored together in a collection\&. Implementing classes should make use of a private constructor\&. "
.ti -1c
.RI "interface \fBISubscribe\fP"
.br
.RI "Represents a subscriber object to be used with a notifier to receive updates\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
