.TH "EarnShardsForCards.Server.Areas.Identity.Pages.Account.Manage" 3 "Sat Apr 23 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Areas.Identity.Pages.Account.Manage
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChangePasswordModel\fP"
.br
.ti -1c
.RI "class \fBDeletePersonalDataModel\fP"
.br
.ti -1c
.RI "class \fBDisable2faModel\fP"
.br
.ti -1c
.RI "class \fBDownloadPersonalDataModel\fP"
.br
.ti -1c
.RI "class \fBEmailModel\fP"
.br
.ti -1c
.RI "class \fBEnableAuthenticatorModel\fP"
.br
.ti -1c
.RI "class \fBExternalLoginsModel\fP"
.br
.ti -1c
.RI "class \fBGenerateRecoveryCodesModel\fP"
.br
.ti -1c
.RI "class \fBIndexModel\fP"
.br
.ti -1c
.RI "class \fBManageNavPages\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "class \fBPersonalDataModel\fP"
.br
.ti -1c
.RI "class \fBResetAuthenticatorModel\fP"
.br
.ti -1c
.RI "class \fBSetPasswordModel\fP"
.br
.ti -1c
.RI "class \fBShowRecoveryCodesModel\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "class \fBTwoFactorAuthenticationModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
