.TH "EarnShardsForCards.Shared.Data.Interfaces.ISubscribe" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Shared.Data.Interfaces.ISubscribe \- Represents a subscriber object to be used with a notifier to receive updates\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNotify\fP ()"
.br
.RI "Handle notification from notifier object "
.in -1c
.SH "Detailed Description"
.PP 
Represents a subscriber object to be used with a notifier to receive updates\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
