.TH "EarnShardsForCards.Server.Models.ApplicationUser" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Models.ApplicationUser
.SH SYNOPSIS
.br
.PP
.PP
Inherits IdentityUser\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
