.TH "EarnShardsForCards.Server.Areas.Identity.Pages.Account" 3 "Sat Apr 23 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Areas.Identity.Pages.Account
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessDeniedModel\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "class \fBConfirmEmailChangeModel\fP"
.br
.ti -1c
.RI "class \fBConfirmEmailModel\fP"
.br
.ti -1c
.RI "class \fBExternalLoginModel\fP"
.br
.ti -1c
.RI "class \fBForgotPasswordConfirmation\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "class \fBForgotPasswordModel\fP"
.br
.ti -1c
.RI "class \fBLockoutModel\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "class \fBLoginModel\fP"
.br
.ti -1c
.RI "class \fBLoginWith2faModel\fP"
.br
.ti -1c
.RI "class \fBLoginWithRecoveryCodeModel\fP"
.br
.ti -1c
.RI "class \fBLogoutModel\fP"
.br
.ti -1c
.RI "class \fBRegisterConfirmationModel\fP"
.br
.ti -1c
.RI "class \fBRegisterModel\fP"
.br
.ti -1c
.RI "class \fBResendEmailConfirmationModel\fP"
.br
.ti -1c
.RI "class \fBResetPasswordConfirmationModel\fP"
.br
.RI "This API supports the ASP\&.NET Core \fBIdentity\fP default UI infrastructure and is not intended to be used directly from your code\&. This API may change or be removed in future releases\&. "
.ti -1c
.RI "class \fBResetPasswordModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
