.TH "EarnShardsForCards.Shared.Data.GinRummy.GinRummyBoard" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Shared.Data.GinRummy.GinRummyBoard \- A \fBGinRummyBoard\fP represents the real-world table that Gin Rummy is played on\&. In the aspect of the virtual game, it is used as an object to hold the other objects\&. The one game support capability it includes not typical of a normal table is knowing whether the pass button is being shown\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGinRummyBoard\fP ()"
.br
.RI "Create a new \fBGinRummyBoard\fP holding information related to the board and its players "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBGinRummyComputerPlayer\fP< \fBPlayingCard\fP > \fBComputerPlayer\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBPlayer\fP< \fBPlayingCard\fP > \fBPlayer\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBPlayingCardDeck\fP \fBDeck\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBDiscardPile\fP< \fBPlayingCard\fP > \fBDiscardPile\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBGinRummyBoard\fP represents the real-world table that Gin Rummy is played on\&. In the aspect of the virtual game, it is used as an object to hold the other objects\&. The one game support capability it includes not typical of a normal table is knowing whether the pass button is being shown\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
