.TH "EarnShardsForCards.Server.Data.Migrations.ApplicationDbContextModelSnapshot" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Data.Migrations.ApplicationDbContextModelSnapshot
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModelSnapshot\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBBuildModel\fP (ModelBuilder modelBuilder)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
