.TH "EarnShardsForCards.Test.Models" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Test.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCardTest\fP"
.br
.RI "Tests the implementations of the Card class "
.ti -1c
.RI "class \fBPlayingCardTest\fP"
.br
.RI "Tests the PlayingCard class to ensure that it conforms to that specified in the design document\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
