.TH "EarnShardsForCards.Server.Areas.Identity.Pages.Account.Manage.DownloadPersonalDataModel" 3 "Sat Apr 23 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Areas.Identity.Pages.Account.Manage.DownloadPersonalDataModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDownloadPersonalDataModel\fP (UserManager< \fBApplicationUser\fP > userManager, ILogger< \fBDownloadPersonalDataModel\fP > logger)"
.br
.ti -1c
.RI "IActionResult \fBOnGet\fP ()"
.br
.ti -1c
.RI "async Task< IActionResult > \fBOnPostAsync\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
