.TH "EarnShardsForCards.Server.Controllers.OidcConfigurationController" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Controllers.OidcConfigurationController
.SH SYNOPSIS
.br
.PP
.PP
Inherits Controller\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOidcConfigurationController\fP (IClientRequestParametersProvider clientRequestParametersProvider, ILogger< \fBOidcConfigurationController\fP > logger)"
.br
.ti -1c
.RI "IActionResult \fBGetClientRequestParameters\fP ([FromRoute] string clientId)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IClientRequestParametersProvider \fBClientRequestParametersProvider\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
