.TH "EarnShardsForCards.Server.Areas.Identity.Pages.Account.Manage.PersonalDataModel" 3 "Sat Apr 23 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Areas.Identity.Pages.Account.Manage.PersonalDataModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPersonalDataModel\fP (UserManager< \fBApplicationUser\fP > userManager, ILogger< \fBPersonalDataModel\fP > logger)"
.br
.ti -1c
.RI "async Task< IActionResult > \fBOnGet\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
