.TH "EarnShardsForCards.Server.Data.ApplicationDbContext" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Data.ApplicationDbContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApiAuthorizationDbContext< ApplicationUser >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApplicationDbContext\fP (DbContextOptions options, IOptions< OperationalStoreOptions > operationalStoreOptions)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
