.TH "EarnShardsForCards.Server.Data.Migrations.CreateIdentitySchema" 3 "Tue Apr 26 2022" "Earn Cards for Shards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EarnShardsForCards.Server.Data.Migrations.CreateIdentitySchema
.SH SYNOPSIS
.br
.PP
.PP
Inherits Migration\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUp\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBDown\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBBuildTargetModel\fP (ModelBuilder modelBuilder)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Earn Cards for Shards from the source code\&.
